config/routes.rb
Rails.application.routes.draw do
  get 'pages/info'
  resources :ideas
  match 'ideas/:id/approve', :to => 'ideas#approve', :as => 'ideas_approve', :via => :post
  match 'ideas/:id/reject', :to => 'ideas#reject', :as => 'ideas_reject', :via => :post
  root to: redirect('ideas')
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
class Idea < ApplicationRecord
    mount_uploader :picture, PictureUploader
    enum status: [:pending, :approved, :rejected]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /ideas/1/approve
  def approve
    @idea = Idea.find(params[:id])
    @idea.update_attribute(:status, :approved)
    respond_to do |format|
        format.html { redirect_to ideas_url, notice: 'Idea was successfully approved.' }
        format.json { head :no_content }
    end
  end

  # POST /ideas/1/reject
  def reject
    @idea = Idea.find(params[:id])
    @idea.update_attribute(:status, :rejected)
    respond_to do |format|
        format.html { redirect_to ideas_url, notice: 'Idea was successfully rejected.' }
        format.json { head :no_content }
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully removed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def idea_params
      params.require(:idea).permit(:name, :description, :picture, :status)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/ideas/_form.html.erb
<%= form_with(model: idea) do |form| %>
  <% if idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
        <% idea.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/ideas/_form_edit.html.erb
<%= form_with(model: idea) do |form_edit| %>
  <% if idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
        <% idea.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form_edit.label :name %>
  </div>
  <div class="field">
    <%= form_edit.text_field :name %>
  </div>

  <div class="field">
    <%= form_edit.label :description %>
  </div>
  <div class="field">
    <%= form_edit.text_area :description %>
  </div>

  <div class="field">
    <%= form_edit.label :picture %>
  </div>
  <div class="field">
    <%= form_edit.file_field :picture %>
  </div>

  <div class="field">
    <%= form_edit.label :status %>
  </div>
  <div class="field">
    <%= form_edit.radio_button :status, "Approved" %>
    <%= form_edit.label :status_approved, "Approve" %>
    <%= form_edit.radio_button :status, "Rejected" %>
    <%= form_edit.label :status_rejected, "Reject" %>
  </div>

  <div class="actions">
    <%= form_edit.submit %>
  </div>
<% end %>

app/views/ideas/_form_new.html.erb
<%= form_with(model: idea) do |form_new| %>
  <% if idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
        <% idea.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form_new.label :name %>
  </div>
  <div class="field">
    <%= form_new.text_field :name %>
  </div>

  <div class="field">
    <%= form_new.label :description %>
  </div>
  <div class="field">
    <%= form_new.text_area :description %>
  </div>

  <div class="field">
    <%= form_new.label :picture %>
  </div>
  <div class="field">
    <%= form_new.file_field :picture %>
  </div>

  <div class="actions">
    <%= form_new.submit %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editing Idea</h1>

<%= render 'form_edit', idea: @idea %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %> |
<%= link_to 'Delete', @idea, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/ideas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ideas</h1>

<div class="row justify-content-end">
    <div class="col-2">
      <%= link_to 'Create New Idea', new_idea_path, class: "btn btn-success" %>
    </div>
</div>

<section class="home">
    </section>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Picture</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= link_to idea.name, idea %></td>
        <td><%= idea.description %></td>
        <td><%= image_tag idea.picture_url, width: '50%' if idea.picture.present? %></td>
        <td><%= idea.status.humanize %></td>
        <td><%= link_to 'Approve', ideas_approve_url(idea), :confirm => "Are you sure want to approve it?", :method => :post, class: "btn btn-success" %></td>
        <td><%= link_to 'Reject', ideas_reject_url(idea), :confirm => "Are you sure want to reject it?", :method => :post, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/ideas/new.html.erb
<h1>New Idea</h1>

<%= render 'form_new', idea: @idea %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Detail Idea</h1>

<p>
  <strong>Name:</strong>
  <%= @idea.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @idea.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@idea.picture_url, width: 600) if @idea.picture.present? %>
</p>

<p>
  <strong>Status:</strong>
  <%= @idea.status %>
</p>

<%= link_to 'Edit', edit_idea_path(@idea) %> |
<%= link_to 'Back', ideas_path %> |
<%= link_to 'Delete', @idea, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container">
    <a class="navbar-brand" href="/">
    <img src="<%= asset_path( 'idea.png' ) %>" alt="" width="30" height="30" class="d-inline-block align-top">
    The Idea App
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="nav justify-content-end" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
        <li class="nav-item inactive <%= 'active' if params[:selected] != 'ideas' %>">
            <a class="nav-link" href="/ideas?selected=ideas">Ideas</a>
        </li>
        <li class="nav-item inactive <%= 'active' if params[:selected] != 'info' %>">
            <a class="nav-link" href="/pages/info?selected=info">Info</a>
        </li>
        </ul>
    </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LearnRuby</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/navigation' %>
      <%= yield %>
    </div>

    <footer>
    <div class="container">
      Rails Girls <%= Time.now.year %>
    </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/pages/info.html.erb
<h1>Pages#info</h1>
<p>Find me in app/views/pages/info.html.erb</p>